### ISSUE TITLE
does it support >8 bit registers?

### ISSUE THREAD

**Issue by ModPunchtree** [ac101m/redmon#8]
registers that are >8 bit may also often have a 2 block gap between each layer of 8 bits (for boosting signal strength),
it would need to be able to support these gaps for it to be useful beyond 8 bit.

also does it support different types of redstone conponents?
so for example - you could use powered redstone dust to mark a 1 and unpowered dust to mark a 0,
or a powered repeater or repeater lock to mark a 1 and the opposite to mark a 0,
or for SR latches - you could use a powered torch to mark a 1 and an unpowered torch to mark a 0,

it is also posssible that the data inside of the register is inverted (so unpowered marks a 1 and powered marks a 0), so being able to swap the conditions can be important,

i have been looking for a mod to do this for years but and the recent redstone tools mod from mattbatwings fails to support >8 bit registers unfortunately, but maybe this mod could be what i am looking for?

**Comment by ac101m** [comment]
At the moment it can only do repeater registers, though I plan to add support other blocks as well. Hex registers are probably the next thing to support, dust, torches etc can also be done. It can't do inversion yet, but yes that's defo something I can add support for! Will stick it on the list :wink: 

At the moment it supports registers up to 64 bits, but that's just because I store register state in a 64 bit word, there's no reason I can't add support arbitrarily large registers, it's just not a priority at the moment. The only restriction is that the bits of the register have to be organized along a straight line in the world. I plan to address this in the near future by letting users append bits to a register.

To explain how this works, you add a register by looking _through_ it and running a command. for example if you run `/redmon register create r0 --bits=32`, the mod will look for 32 repeaters along the direction you are currently looking.

Sounds to me like this might be exactly what you need! It's a bit rough around the edges at the moment, but I plan to improve it gradually over time.

P.S. I'll also add proper instructions to the readme some point so people don't need to raise issues to ask questions!
